#!/usr/bin/env python
#-*- coding: UTF-8 -*-

from StringIO import StringIO
import yaml
import sys
import os.path
import jinja2

filename = "/code/src/crons.yml"

if os.path.isfile(filename):
    print "The crons.yml exists"

    with open(filename, 'r') as f:
        content = f.read()

    # Parseamos el yml
    try:
        crons = yaml.load(content)
        crons_parsed = crons
        print "Parse OK, installing the new crontab."
    except:
        print "Error parsing the yml crons file. Cleaning the django's crontab."
        crons_parsed = {}
else:
    print "There is not file in: %s. Cleaning the django's crontab." % filename
    crons_parsed = {}


# Render the crontab file with jinja
templateLoader = jinja2.FileSystemLoader( searchpath="conf" )
templateEnv = jinja2.Environment( loader=templateLoader )
template_filename = "/usr/local/src/install_crons/crons.template"
template = templateEnv.get_template( template_filename )
crontab = template.render( crons_parsed=crons_parsed )

# Install the new contrab to the django user
cronfile = open('/etc/cron.d/django', 'w+')
cronfile.write(crontab)
