#!/bin/sh
printenv 

UID=$(id -u)
CMD="pew-in env python manage.py $@"

echo "---> Ejecutando  $CMD..."
cd /code/src
if [ $UID = 0 ]; then
   echo "ID0!!!!"
   su -c "$CMD" django
else
   sh -c "$CMD"
fi
